### ISSUE TITLE
Implement pytest as test suite run in the CI

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/sunglass#2]
### Problem

There are no tests - yet - neither a CI system running them in different platforms and python versions.

### Proposed solution

Implement  a CI system that uses `pytest` to run tests once they are in place. `Sunglass` uses `poetry` as the package manager, therefore something similar to what is done in the [StrainMap project](https://github.com/ImperialCollegeLondon/strainmap/blob/fe08324240832285332b03ca86dc3778337bf627/.github/workflows/ci.yml#L16) should work. 

Good first issue... to get familiar with testing in a CI system.

**Comment by AlexNDRmac** [comment]
Hi @dalonsoa, I would like to help you with this.

**Comment by dalonsoa** [comment]
Absolutely! Go ahead with it! Let me know if you need any help or clarification.

**Comment by AlexNDRmac** [comment]
Hi @dalonsoa. Could you please take a look at workflow [log](https://github.com/AlexNDRmac/sunglass/actions/runs/3287543084/jobs/5416833259#step:6:145) and point me what's wrong with package install step? I've already tried with dependencies update, with changing package version by hand... nothing helps.
What I'm missing with project install step? Thanks.

**Comment by dalonsoa** [comment]
I'm not totally sure, to be honest. I'd suggest you update your branch from `develop` has we have upgraded the version of the dependencies that, for whatever reason, was very old - see #12 .

The problem seems to be with trying to build `solcore`. This should be solved within the next few days when we merge [this PR ](https://github.com/qpv-research-group/solcore5/pull/229) and release a new version with binary wheels for all platforms. So, if the first suggestion does not work, I'd suggest you wait until that is done.

**Comment by AlexNDRmac** [comment]
@dalonsoa pls check PR with CI feature :)

**Comment by dalonsoa** [comment]
@all-contributors please add @AlexNDRmac for infrastructure and test

**Comment by dalonsoa** [comment]
Fantastic! Many thanks!
